### GET - Metadata
GET http://localhost:4004/odata/v4/purchase-order/$metadata

### GET - Purchase Order
GET http://localhost:4004/odata/v4/purchase-order/PurchaseOrder

### POST - Purchase Order
POST http://localhost:4004/odata/v4/purchase-order/PurchaseOrder
Content-Type: application/json
Accept: application/json

{
    "PurchaseOrder": "4500000002",
    "PurchaseOrderType_ID": "e4d4g4f3-4d5e-7f6g-1b2c-423456789001",
    "PurchasingOrganization_ID": "d3c3f3e2-3c4d-6e5f-0a1b-323456789001",
    "CompanyCode_ID": "c2b2e2d1-2b3c-5d4e-9f0a-223456789002",
    "Supplier_ID": "b1a1e1c0-1a2b-4c3d-8e9f-123456789005",
    "Language_code": "EN",
    "PurchaseOrderDate": "2025-09-20",
    "PurchasingGroup": "001",
    "DocumentCurrency_code": "USD",
    "PurchasingProcessingStatus_code": "A"
}

### DELETE - Purchase Order
DELETE http://localhost:4004/odata/v4/purchase-order/PurchaseOrder(ID='284cb416-defa-432d-9a50-b6a990827e74',PurchaseOrder='4500000002')

### UPDATE - Purchase Order
PATCH  http://localhost:4004/odata/v4/purchase-order/PurchaseOrder(ID='6775096c-649b-4eb6-a1d7-e6b3f75b1cec',PurchaseOrder='4500000002')
Content-Type: application/json
Accept: application/json

{
    "PurchaseOrder": "4500000002",
    "PurchaseOrderType_ID": "e4d4g4f3-4d5e-7f6g-1b2c-423456789001",
    "PurchasingOrganization_ID": "d3c3f3e2-3c4d-6e5f-0a1b-323456789001",
    "CompanyCode_ID": "c2b2e2d1-2b3c-5d4e-9f0a-223456789002",
    "Supplier_ID": "b1a1e1c0-1a2b-4c3d-8e9f-123456789005",
    "Language_code": "ES",
    "PurchaseOrderDate": "2025-09-20",
    "PurchasingGroup": "001",
    "DocumentCurrency_code": "EUR",
    "PurchasingProcessingStatus_code": "A"
}